/*
 * This file is generated by jOOQ.
 */
package com.test.jooq.codegen.tables.pojos;


import com.test.jooq.codegen.tables.interfaces.IUserMsg;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMsg implements IUserMsg {

    private static final long serialVersionUID = 102062870;

    private Integer id;
    private Integer uid;
    private String  msg;

    public UserMsg() {}

    public UserMsg(IUserMsg value) {
        this.id = value.getId();
        this.uid = value.getUid();
        this.msg = value.getMsg();
    }

    public UserMsg(
        Integer id,
        Integer uid,
        String  msg
    ) {
        this.id = id;
        this.uid = uid;
        this.msg = msg;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public Integer getUid() {
        return this.uid;
    }

    @Override
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    @Override
    public String getMsg() {
        return this.msg;
    }

    @Override
    public void setMsg(String msg) {
        this.msg = msg;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserMsg (");

        sb.append(id);
        sb.append(", ").append(uid);
        sb.append(", ").append(msg);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserMsg from) {
        setId(from.getId());
        setUid(from.getUid());
        setMsg(from.getMsg());
    }

    @Override
    public <E extends IUserMsg> E into(E into) {
        into.from(this);
        return into;
    }
}
