spring:
  datasource:
    url: jdbc:mysql://47.106.74.177:13306/test_jpa?allowPublicKeyRetrieval=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hd
    password: hd123456

  jpa:
    hibernate:
      ddl-auto: update #自动更新
      show-sql: true  #日志中显示sql语句
      format_sql: true