spring:
  rabbitmq:
    host: 120.78.189.168
    port: 5672
    username: god
    password: god123456
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true

#    listener:
#      direct:
#        # acknowledge-mode 签收模式三种
#        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual