/*
 * This file is generated by jOOQ.
 */
package com.test.jooq.codegen.tables.interfaces;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用户表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUser extends Serializable {

    /**
     * Setter for <code>test.user.id</code>. ID
     */
    public void setId(Integer value);

    /**
     * Getter for <code>test.user.id</code>. ID
     */
    public Integer getId();

    /**
     * Setter for <code>test.user.name</code>. 名称
     */
    public void setName(String value);

    /**
     * Getter for <code>test.user.name</code>. 名称
     */
    public String getName();

    /**
     * Setter for <code>test.user.age</code>. 年龄
     */
    public void setAge(Integer value);

    /**
     * Getter for <code>test.user.age</code>. 年龄
     */
    public Integer getAge();

    /**
     * Setter for <code>test.user.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value);

    /**
     * Getter for <code>test.user.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser
     */
    public void from(com.test.jooq.codegen.tables.interfaces.IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser
     */
    public <E extends com.test.jooq.codegen.tables.interfaces.IUser> E into(E into);
}
