# 项目端口
server:
  port: 8080
# 项目访问路径
  servlet:
    context-path: /test

spring:
  redis:
    database: 0
    timeout: 3000
    password: 123456
    # 单节点模式
    host: 127.0.0.1
    port: 6379

    # 哨兵模式
#      sentinel:
#        master: mymaster #主服务器所在集群名称
#        nodes: 192.168.65.60:26379,192.168.65.60:26380,192.168.65.60:26381

    #集群模式
#    cluster:
#      nodes: 192.168.50.61:8001,192.168.50.62:8002,192.168.50.63:8003,192.168.50.61:8004,192.168.50.62:8005,192.168.50.63:8006
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000


    # 连接池，默认使用lettuce客户端redis连接池
    lettuce:
      pool:
        max-idle: 8 # 连接池中的最大空闲连接数
        min-idle: 0 # 连接池中的最小空闲连接数
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

#    jedis:
#      pool:
#        max-idle: 8 # 连接池中的最大空闲连接数
#        min-idle: 0 # 连接池中的最小空闲连接数
#          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）