
package com.test.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-08-01T15:27:41.429+08:00
 * Generated source version: 2.7.18
 * 
 */
 
public class HelloWS_HelloWSImplPort_Server{

    protected HelloWS_HelloWSImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWSImpl();
        String address = "http://127.0.0.1:8989/test-webservice/hellows";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloWS_HelloWSImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
